services:
  # Service de développement
  portfolio-dev:
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
    networks:
      - portfolio-network
      
  # Service de production
  portfolio:
    build: 
      context: .
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: always
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
